-- Josh Keller
-- Creating the driver table
-- Used for the "job search" aspect of the portal or other integrations for employer use
-- Stores driver information for employer ease of access

CREATE TABLE DRIVER(
	DID INT PRIMARY KEY,
	DPosition NVARCHAR(50),
	D_First NVARCHAR(50),
	D_Last NVARCHAR(50),
	D_Hometown NVARCHAR(50),
	D_LNum NVARCHAR(50)
);


-- Insert data into this table
-- Mock data, generated by ChatGPT. Prompt in README


INSERT INTO DRIVER (DID, DPosition, D_First, D_Last, D_Hometown, D_LNum) 
VALUES 
(1, 'Flatbed Driver', 'John', 'Smith', 'New York', 'DL12345'),
(2, 'Auto Hauler', 'Emily', 'Johnson', 'Los Angeles', 'DL67890'),
(3, 'Freight Hauler', 'Michael', 'Williams', 'Chicago', 'DL24680'),
(4, 'Delivery Driver', 'Sarah', 'Brown', 'Houston', 'DL13579'),
(5, 'Tanker Driver', 'James', 'Davis', 'Phoenix', 'DL86420'),
(6, 'Courier', 'Jessica', 'Martinez', 'Philadelphia', 'DL97531'),
(7, 'Dump Truck Driver', 'David', 'Anderson', 'San Antonio', 'DL35791'),
(8, 'Long Haul Driver', 'Jennifer', 'Garcia', 'San Diego', 'DL68024'),
(9, 'Bus Driver', 'Robert', 'Rodriguez', 'Dallas', 'DL24681'),
(10, 'School Bus Driver', 'Lisa', 'Lopez', 'San Jose', 'DL24682'),
(11, 'Transit Driver', 'Daniel', 'Wilson', 'Austin', 'DL24683'),
(12, 'Shuttle Driver', 'Megan', 'Hernandez', 'Jacksonville', 'DL24684'),
(13, 'Truck Driver', 'William', 'Walker', 'Indianapolis', 'DL24685'),
(14, 'Forklift Operator', 'Ashley', 'Young', 'San Francisco', 'DL24686'),
(15, 'Lift Truck Operator', 'Christopher', 'King', 'Columbus', 'DL24687'),
(16, 'Van Driver', 'Amanda', 'Scott', 'Charlotte', 'DL24688'),
(17, 'Tow Truck Driver', 'Matthew', 'Green', 'Fort Worth', 'DL24689'),
(18, 'Garbage Truck Driver', 'Samantha', 'Baker', 'Detroit', 'DL24690'),
(19, 'Loader Operator', 'Andrew', 'Hill', 'Seattle', 'DL24691'),
(20, 'Crane Operator', 'Elizabeth', 'Perez', 'Denver', 'DL24692');

-- Ensure successful data entry

SELECT * FROM DRIVER;

-- Create POI Table
-- This table is for Points of Interest along a given route a driver may pick
-- A core element of one of the projects we were merging is finding POI along a route
-- To find POI, POI must be in this table

CREATE TABLE POI(
	POI_ID INT PRIMARY KEY,
	POI_Name NVARCHAR(50),
	POI_Add_Num INT,
	POI_Street NVARCHAR(50),
	POI_CITY NVARCHAR(50),
	POI_STATE VARCHAR(50),
	POI_ZIP int
);

-- Insert mock data generated by ChatGPT
-- Prompt in READ
-- Inserting mock data into POI table

INSERT INTO POI (POI_ID, POI_Name, POI_Add_Num, POI_Street, POI_City, POI_ZIP)
VALUES
(1, 'Rest Area 1', 100, 'Highway 1', 'Springfield', 'IL', 62701),
(2, 'Truck Stop 24/7', 200, 'Interstate 55', 'Lexington', 'KY', 40502),
(3, 'Travel Plaza', 300, 'Highway 101', 'Bakersfield', 'CA', 93301),
(4, 'Rest Haven', 400, 'Interstate 80', 'Omaha', 'NE', 68101),
(5, 'Roadside Oasis', 500, 'Highway 20', 'Boise', 'ID', 83701);

-- Ensure data is entered

SELECT * FROM POI;



