use MIST353A3
go
--Jayden Donham start
insert into Occupation (Position, Wage)
values
('Doordash Driver', '15'),
('Uber Driver', '25'),
('Trucker', '50');
go

insert into Location (State, City, Zip)
values
('West Virginia', 'Morgantown', '26505'),
('Pennsylvania', 'Pittsburgh', '15106'),
('Ohio', 'Cleveland', '44101');
go
--Jayden Donham end

--Josh Keller
-- Insert data into DRIVER table
-- Mock data, generated by ChatGPT. Prompt in README


INSERT INTO DRIVER (DID, DPosition, D_First, D_Last, D_Hometown, D_LNum) 
VALUES 
(1, 'Flatbed Driver', 'John', 'Smith', 'New York', 'DL12345'),
(2, 'Auto Hauler', 'Emily', 'Johnson', 'Los Angeles', 'DL67890'),
(3, 'Freight Hauler', 'Michael', 'Williams', 'Chicago', 'DL24680'),
(4, 'Delivery Driver', 'Sarah', 'Brown', 'Houston', 'DL13579'),
(5, 'Tanker Driver', 'James', 'Davis', 'Phoenix', 'DL86420'),
(6, 'Courier', 'Jessica', 'Martinez', 'Philadelphia', 'DL97531'),
(7, 'Dump Truck Driver', 'David', 'Anderson', 'San Antonio', 'DL35791'),
(8, 'Long Haul Driver', 'Jennifer', 'Garcia', 'San Diego', 'DL68024'),
(9, 'Bus Driver', 'Robert', 'Rodriguez', 'Dallas', 'DL24681'),
(10, 'School Bus Driver', 'Lisa', 'Lopez', 'San Jose', 'DL24682'),
(11, 'Transit Driver', 'Daniel', 'Wilson', 'Austin', 'DL24683'),
(12, 'Shuttle Driver', 'Megan', 'Hernandez', 'Jacksonville', 'DL24684'),
(13, 'Truck Driver', 'William', 'Walker', 'Indianapolis', 'DL24685'),
(14, 'Forklift Operator', 'Ashley', 'Young', 'San Francisco', 'DL24686'),
(15, 'Lift Truck Operator', 'Christopher', 'King', 'Columbus', 'DL24687'),
(16, 'Van Driver', 'Amanda', 'Scott', 'Charlotte', 'DL24688'),
(17, 'Tow Truck Driver', 'Matthew', 'Green', 'Fort Worth', 'DL24689'),
(18, 'Garbage Truck Driver', 'Samantha', 'Baker', 'Detroit', 'DL24690'),
(19, 'Loader Operator', 'Andrew', 'Hill', 'Seattle', 'DL24691'),
(20, 'Crane Operator', 'Elizabeth', 'Perez', 'Denver', 'DL24692');
GO

-- Insert mock data generated by ChatGPT
-- Prompt in READMME
-- Inserting mock data into POI table

INSERT INTO POI (POI_ID, POI_Name, POI_Add_Num, POI_Street, POI_City, POI_State, POI_ZIP)
VALUES
(1, 'Rest Area 1', 100, 'Highway 1', 'Springfield', 'Illinois', 62701),
(2, 'Truck Stop 24/7', 200, 'Interstate 55', 'Lexington', 'Kentucky', 40502),
(3, 'Travel Plaza', 300, 'Highway 101', 'Bakersfield', 'California', 93301),
(4, 'Rest Haven', 400, 'Interstate 80', 'Omaha', 'Nebraska', 68101),
(5, 'Roadside Oasis', 500, 'Highway 20', 'Boise', 'Idaho', 83701);
GO

--Josh Keller end